### PR TITLE
Fixing formulas in Rmodels.Rmd

### PR DESCRIPTION
**Pull request by vliublinska**
Steve, I noticed several inaccuracies in formulas listed in Rmodels.Rmd - see suggested changes. Would be happy to discuss further!

### CODE REVIEW

**Comment by stevenworthington** [comment]
Hi Victoria, thanks for reviewing this! And thanks for picking up on some typos in the mixed model description and variable tables, and especially: logit(p(hypev_i=1))! Having reviewed it though, I'm pretty happy with how everything else looks - why do you suggest changing all the betas to bs?

**Comment by vliublinska** [comment]
Oh, this was just a small formality. In general, models that describe _observed_ responses (as opposed to _responses as random variables_) are written with b's vs. betas (aka, estimates vs. theoretical parameters) and e's vs. epsilons. This is not a huge deal, just an automatic impulse to make it look like what I'm used to seeing in the literature. It is probably fine either way for the purpose of the workshop.

**Comment by stevenworthington** [comment]
Ah, I see. I thought perhaps you were from a domain in which betas are always used for standardized coefficients and b's for unstandardized. Here, I want unstandardized theoretical parameters, not estimates. The reason for including the formulae was to relate the R formula syntax back to the theoretical model. Though by trying to be consistent across the formulae I definitely occasionally stray into some unconventional notation - like including an error term for the logistic model. But, my preference is to include it, even though it's fixed at pi^2/3 rather than estimated.

**Comment by vliublinska** [comment]
While I would go either way on b vs. beta, the error term in the logistic regression would always be a serious red flag in any stats class that I've taken (or taught). It doesn't really have any conceptual meaning and may rub the wrong way someone with a more classic training (essentially, look like an unfortunate typo). I think keeping it warrants at least a short explanation below that points out why it was deliberate! (Also, I'm not exactly sure what you mean by "fixed at pi^2/3" here, could you please elaborate?)

**Comment by stevenworthington** [comment]
The error term has meaning when logistic models are conceptualized in a latent variable framework, which is one popular way of understanding discrete choice models. In that case, the errors are assumed to follow a logistic distribution and, because the scale of the latent outcome can't be determined, the errors are fixed at pi^2/3 - the variance of the logistic distribution. 

But, I take your point about it potentially rubbing people the wrong way - this approach to thinking about logistic models is much more often used in a mixed effects context anyway and much less often in a single-level GLM context, so it will likely be confusing without further explanation and that's not the point or focus of the workshop. I'll use the more traditional notation.

**Comment by vliublinska** [comment]
Sure, I see where this is coming from. I definitely agree that a latent-variable interpretation of the logistic regression is very useful and certainly popular in some disciplines (psychology, educational testing etc.). However, I was just merely concerned with the notation. The latent variable model is usually specified using a latent response, which is unobserved and has to be defined separately. This adds a lot of complication to the description of the problem which, I definitely agree with you, would be an unnecessary complication in this case.

**Comment by stevenworthington** [comment]
Yeah, originally, in my old forked version I had a more general notation for GLMs, with a latent response being related to the linear predictor through the link function - that's kind of how I like to think about it and teach it. But somewhere along the line, in the midst of hasty revisions and adding content, the notation seems to have become a bit of a Frankenstein's monster. This is why it's great to have an extra pair of eyes to look it over. This isn't a stats class anyway, so simple is probably better. Thanks!

**Comment by stevenworthington** [comment]
Closing this, but have implemented almost all of Victoria's corrections.

**Pull request closed without merging**
